# Generated by Django 5.0.3 on 2024-03-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=15)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='miembro_imagen')),
                ('estado', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
